version: "2.3"

services:
  app:
    build:
      context: .
      # a shortcut for debug multi-stage build stage
      # target: builder
      args:
        NPM_TOKEN: $NPM_TOKEN
        GITHUB_TOKEN: $GITHUB_TOKEN
    environment:
      PORT: 3000
    volumes:
    # api backend usually requires runtime config, e.g. env
    - ".env.demo:/srv/.env"
    ports:
    - "4000:3000"
    # entrypoint overwrite to keep the container for debug
    # entrypoint: tail -f /dev/null
